### ISSUE TITLE
Can't stop current drawing

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#10]
Moreover, it's not possible to skip once you've started to draw. Line deletion goes here as well.

**Comment by AlNedorezov** [comment]
@nmingazov, what do you mean by "skip"? Is it skipping the markup of the current image via clicking the "skip" button in Toloka (which works), or maybe, cancelling the markup of the current object (drawing of the polygon)?

**Comment by nmingazov** [comment]
As far as I remember it's not possible to press "skip" button in Toloka. For canceling the markup of current drawing I've used "stop" word in the issue title.

**Comment by AlNedorezov** [comment]
@nmingazov, thank you for the clarification.
It is possible to skip the markup of the current image via clicking the "skip" button in Toloka (see [screencast](https://drive.google.com/file/d/0B_A9nop45WwKbFdZSmEzYTQzNFU/view?usp=sharing)).
As for canceling the markup of current drawing and line deletion, I think this functionality may duplicate the one planned for "history".

**Comment by ruslanmustafin** [comment]
Fixed in 298aaf67a3b2148a9d98aa7760e35d0a2492d69a. 

You can now cancel drawing of polygons by right clicking on the image.

**Comment by AlNedorezov** [comment]
Line deletion was implemented as well.
Quote from [Adding annotations to an image wiki page](https://github.com/innosoft-pro/label-them/wiki/Adding-annotations-to-an-image):
> HINT: you can use Ctrl+Z to remove an accidentally added point. Similarly, press Ctrl+Shift+Z to re-add a previously removed point.
