### ISSUE TITLE
Offline approvement is not working

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#21]
Basically, I can't see contours when I'm trying to understand should I approve or rejected the image.
<img width="1227" alt="screen shot 2017-06-27 at 18 55 50" src="https://user-images.githubusercontent.com/7488302/27597302-a5d5d6f4-5b6a-11e7-9416-317c21ae0d9d.png">

Nevertheless, when I'm downloading results rejected by me they actually have something inside. In the archive below you can find example `.tsv` results - all and rejected only.

[ExampleTSV.zip](https://github.com/innosoft-pro/label-them/files/1105946/ExampleTSV.zip)

**Comment by AlNedorezov** [comment]
@nmingazov, delayed acceptance feature was implemented in [version 1.4](https://github.com/innosoft-pro/label-them/releases/tag/v1.4), and is now available in [develop-toloka branch](https://github.com/innosoft-pro/label-them/tree/develop-toloka).
See [this video](http://dropmefiles.com/Ayll6) for usage reference.

**NOTE:** You can also download the source files that are needed to run the system on Yandex Toloka crowdsourcing platform (`main.html`, `app.js`, and `concat.min.css`) from the ["Releases - Version 1.4." repository page](https://github.com/innosoft-pro/label-them/releases/tag/v1.4).
[![Screenshot from 2017-07-09 23-54-27.png](https://s13.postimg.org/bnoyap43b/Screenshot_from_2017-07-09_23-54-27.png)](https://s13.postimg.org/bnoyap43b/Screenshot_from_2017-07-09_23-54-27.png)

**Comment by mihbort** [comment]
I tried your new release and find out the following bugs in delayed acceptance mode:

- Navigation using `hand` instrument isn't working at all
- If I click in empty space, always creates new point. I think it is not needed for acceptance mod.
- Zoom works only to the top left corner. Usually it zooms to the centre.
- During the zoom, points are not moving with the picture and stand still.
- It would be great if near marked blobs will be shown their's classes.

**Comment by AlNedorezov** [comment]
@mihbort, thank you for your feedback.

> Navigation using hand instrument isn't working at all

Please, elaborate more on this. What exactly is not working? If possible, record a screencast showing inappropriate system behavior, provided with your comments.

> It would be great if near marked blobs will be shown their's classes.

We'll take your feedback into account.

As for other points, we are considering whether delayed acceptance users will need to perform minor fixes of (possibly extremely complex) markup submitted by Mechanical Turks, and, consequently, will need to use the full spectrum of markup functionality.

For the release 1.4 we concentrated on the straightforward delayed acceptance functionality, meaning checking out objects marked up by Mechanical Turks, their classes and parameters (which can be viewed in the "Label Parameters" block, after the marked up object was selected with the "Hand" tool).

**Comment by nmingazov** [comment]
@AlNedorezov @mihbort we could close this issue and split the improvements into different tasks, I believe this is a better way to track it. Is it ok for everyone?

**Comment by mihbort** [comment]
@nmingazov It's Ok. In each task I can explain better what is wrong.

**Comment by AlNedorezov** [comment]
@nmingazov, it's ok. I agree that it will be a better way to track issues and improvements.

**Comment by mihbort** [comment]
> - If I click in empty space, always creates new point. I think it is not needed for acceptance mod.
> - During the zoom, points are not moving with the picture and stand still.

I wasn't able to repeat these bug again, so decided not to open such issues. 
What about this issue, I think it can be closed.
