### ISSUE TITLE
Cannot invite trusted users to sandbox if they email is different from @yandex.ru

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#3]
I'm trying to invite my buddy but he can't be invited by form
<img width="1103" alt="screen shot 2017-05-10 at 15 10 05" src="https://cloud.githubusercontent.com/assets/7488302/25897987/d02e2134-3592-11e7-9954-067ad1aabc61.png">
<img width="937" alt="screen shot 2017-05-10 at 15 11 25" src="https://cloud.githubusercontent.com/assets/7488302/25898390/a140b9de-3594-11e7-937f-c86c7b27b9b4.png">

Nevertheless, mailbox with @yandex.ru works fine.

**Comment by ruslanmustafin** [comment]
Most of the users use Yandex accounts to register within the system, but it is also possible to use login via other social networks. If you can register other social networks that provide not only your name and email address, but also a login, then this login could be used to invite trusted users. 

For example Google does not provide logins, as such it is not possible to invite gmail accounts.

**Comment by nmingazov** [comment]
Ok, I've got that. Nevertheless, it would be cool to see that in some instruction like "Inviting trusted users to personal sandbox" or "Making private markup pool", as far as I remember that could be a case for researcher without money, but with students.

**Comment by ruslanmustafin** [comment]
Ok, I added a Wiki page explaning the process of adding trusted users

https://github.com/innosoft-pro/label-them/wiki/Inviting-trusted-users

**Comment by nmingazov** [comment]
Great job. Thanks :)
