### ISSUE TITLE
Rename "Isoccluded" to "Partially covered"

### ISSUE THREAD

**Issue by VyacheslavLukin** [innosoft-pro/label-them#34]
Based on the first commercial run, almost nobody uses Isoccluded flag during labeling. Thus I propose to change flag naming to more general and simple.

**Comment by AlNedorezov** [comment]
@VyacheslavLukin, all of the parameters, including "is occluded" one are configured by Researches themselves during the particular job configuration.
You can change it in the `classesandparameters.js` file (located in the front/json directory), generate a new TSV file to configure a job, and create a new pool to upload this tsv file.
See [Generating a TSV](https://github.com/innosoft-pro/label-them/wiki/Getting-started-YandexToloka#generating-a-tsv) and [Classes and parameters JSON description](https://github.com/innosoft-pro/label-them/wiki/Classes-and-parameters-JSON-description) instructions for reference.

**Comment by VyacheslavLukin** [comment]
My bad. Thanks for the clarification.
