### ISSUE TITLE
generate_tsv silently generates wrong data

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#4]
Given invalid json such as:
```
{
  "classes":
  [
    "car",
    "person",
    "other""
  ],
  "parameters":
  [
    {
      "type": "boolean",
      "name": "is_occluded"
    }
  ]
}
```
generate_tsv.py silently generates invalid tsv file, which leads to empty space in Toloka.

**Comment by ruslanmustafin** [comment]
@nmingazov we added simple validation for incoming JSON params. In case it fails an exception is raised

**Comment by nmingazov** [comment]
Ok, now it fails correctly, thanks :)
