### ISSUE TITLE
Seeing closed project

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#5]
In case when project is already closed it still could be seen by other users.

**Comment by ruslanmustafin** [comment]
@nmingazov could you verify that you have no open pools in any of your projects?

I have tested it just now and having no open pools actually disables a task for trusted users. 

<img width="1207" alt="yandex_toloka" src="https://cloud.githubusercontent.com/assets/11210900/26416104/70b6a358-40bd-11e7-9e07-2e70f27f0c00.png">

**Comment by ruslanmustafin** [comment]
@nmingazov also make sure that the task is not active for a user, as you can indeed see the closed active tasks (a task is considered to be active if a user had started and then abandoned it, but still have time to return and complete it).

**Comment by ruslanmustafin** [comment]
According to Yandex Toloka managers, a user will still be able to access closed projects as long as they are active for that user (i.e. the time for a task has not run out).

However once a user has submitted an active project, they will stop seeing it.

**Comment by nmingazov** [comment]
Ok, if they won't fix that, we should reflect it somewhere in the docs, at least make a warning in getting started document.

**Comment by ruslanmustafin** [comment]
Added a small paragraph about active tasks and ability to access them in the Getting Started page

https://github.com/innosoft-pro/label-them/wiki/Getting-started-YandexToloka

**Comment by nmingazov** [comment]
Ok, closing this one too.
