### ISSUE TITLE
Pictures with no objects can't be submitted

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#6]
There are pictures where are no cars available for markup (empty road). Now they can't be marked up

**Comment by ruslanmustafin** [comment]
We can either allow submission of scenes with empty annotations or we can ask users to skip such pictures.

Allowing submission with no labels may potentially lead to pictures that are not empty being marked as "empty". This can be fixed via "delayed acceptance", a feature in Yandex Toloka that allows you to manually approve submitted annotations, but it will incur additional costs. 

Asking users to skip pictures with empty scenes will lead to incorrect pool completion statistics as skipped pictures are not counted towards the completion. 

@nmingazov let us know what you think.

**Comment by nmingazov** [comment]
Ok, I think that we could try to ask users to skip such images. Nevertheless, UI doesn't even let the user know that empty markup cannot be submitted. Moreover, that also should be reflected in specs for future researchers.

**Comment by AlNedorezov** [comment]
> Nevertheless, UI doesn't even let the user know that empty markup cannot be submitted.

@nmingazov, good point. I think we may inform a user through the notification block above the image if he tries to submit an empty markup.

**Comment by nmingazov** [comment]
Ok, we just need to make sure that user will actually notice this.
