### ISSUE TITLE
On 100% scale picture goes besides the place for it

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#7]
<img width="1240" alt="screen shot 2017-05-10 at 17 10 15" src="https://cloud.githubusercontent.com/assets/7488302/25902935/a692f8de-35a3-11e7-9d51-81fc9107405c.png">

**Comment by nmingazov** [comment]
On 90%
<img width="1280" alt="screen shot 2017-05-10 at 17 19 59" src="https://cloud.githubusercontent.com/assets/7488302/25903401/f1f1ea64-35a4-11e7-88e4-62123be5a7d1.png">

**Comment by AlNedorezov** [comment]
I think this issue may be connected to the issue #9.

**Comment by ruslanmustafin** [comment]
@nmingazov what are the steps to reproduce the issue? 

In our testing environment the task takes almost all of the screen space (see the screenshot below)

<img width="1430" alt="yandex_toloka" src="https://cloud.githubusercontent.com/assets/11210900/26416442/8bdd02a2-40be-11e7-8d89-0dfd2ecd5a85.png">
